### ISSUE TITLE
Não há possibilidade de deletar entidades já cadastradas

### ISSUE THREAD

**Issue by gehazibispo** [lacs-ufpa/mtrix#1]
Permitir deletar _condições_, _experimentos_ e _jogadores_.

**Comment by weslleysammyr** [comment]
Bom, conforme o acordo inicial do projeto, as configurações não deveriam ser apagadas em hipótese alguma, afim de se manter um histórico de todas as configurações.

Caso isto seja necessário agora, entraria como uma funcionalidade a ser implementada.

**Comment by cpicanco** [comment]
Qual era o objetivo do requisito "impedir apagar informações" no escopo do projeto? Se o objetivo era a segurança das configurações, não faz sentido permitir abertamente a edição delas. O problema que enfrentamos foi o "flood" de configurações, uma falha de usabilidade e segurança.

**Comment by weslleysammyr** [comment]
Entendo @cpicanco que a usabilidade possa ser impactada por conta dessa configuração. Porém, o que foi me passado, enquanto no papel de desenvolvedor, foi que o sistema deveria se comportar dessa maneira.

Talvez elencar este item para o escopo de inclusões seria algo relevante, mas aí já depende da avaliação de vocês.
