### ISSUE TITLE
Jogadas travando após abrir e fechar o chat.

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/mtrix#13]
O botão de selecionar as linhas estava ativo, porém não funcionava após abrir o chat.

**Comment by weslleysammyr** [comment]
Item priorizado como possível bug do sistema.

**Comment by weslleysammyr** [comment]
Conforme aferido nos testes local (foi enviado um vídeo em anexo para a Thais), não foi possível simular o comportamento exemplificado.

Caso ainda exista alguma consideração, acrescentar comentário, do contrário pode fechar o ticket.
