### ISSUE TITLE
Requisitos para a execução do projeto de pesquisa de Thais MMGuimarães

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/mtrix#26]
O experimento possui os seguintes requisitos:
### 1. Pontuação individual

Atualmente existe UMA PONTUAÇÃO INDIVIDUAL. Serão necessários DOIS tipos de PONTUAÇÕES INDIVIDUAIS. Em anexo uma imagem de como ficaria a tela do participante:

![contadores-individuais](https://cloud.githubusercontent.com/assets/22668474/19841709/b1668a9e-9ef6-11e6-92db-3b9ede21acc1.png)

1.1 Quando o participante escolher LINHA ÍMPAR PRODUZIRÁ 3 PONTOS DO TIPO A (lado direito do campo INDIVIDUAL).

1.2 Quando o participante escolher LINHA PAR PRODUZIRÁ 1 PONTO DO TIPO B (lado esquerdo do campo INDIVIDUAL).

OBS.:  Ao final da jogada de cada participante deverá ser apresentada esta mensagem para todos os participantes: PARTICIPANTE 'X' PRODUZIU 1 PONTO DO TIPO B(quando for par) OU 3 PONTOS DO TIPO A (quando for ímpar). ESSA MENSAGEM DEVE SER EDITÁVEL PELO PESQUISADOR, no momento que for estruturar seu experimento (essa possibilidade foi solicitada no Issues #23).

OBS.: 'X' é uma variável com nome do participante que jogou. Deve ser possível editar texto das mensagens usando essa variável.
### 2. Pontuação do grupo

**Condição 1**

2.1. Se algum (ou todos) dos participantes escolher LINHA ÍMPAR NÃO PRODUZIRÁ PONTO GRUPO.

OBS.: Ao final da jogada de todos os participantes NÃO deverá ser apresentada nenhuma mensagem.

2.2. Se todos os participantes escolherem LINHAS PARES DE CORES DIFERENTES PRODUZIRÁ 1 PONTO GRUPO (=1 item escolar).

OBS.: Ao final da jogada de todos os participantes deverá ser apresentada esta mensagem a todos os eles: VOCÊS PRODUZIRAM 1 ITEM ESCOLAR.

OBS.: Essa mensagem deve editável pelo pesquisador no momento que for estruturar seu experimento. 

**Condição 2**

Essa condição deverá ser iniciada com 80 itens escolares e 210 pontos do tipo do TIPO A para cada participante. Ou seja, permitir pontuação inicial por condição e não apenas por experimento.

2.3. Se algum (ou todos) dos participantes escolher uma linha IMPAR PERDERÁ 'X' PONTOS DO TIPO A (do lado direito do campo INDIVIDUAL) e 1 PONTO GRUPO (=1 item escolar). 
A quantidade RETIRADA de PONTOS DO TIPO A será de acordo com a linha escolhida pelo participante em sua jogada durante à rodada (ciclo=jogada de todos os membros do grupo):
- O(s) participante(s) que selecionou(ram) LINHA ÍMPAR PERDERÁ(RÃO) 3 PONTOS DO TIPO A.
- O(s) participante(s) que selecionou(ram) LINHA PAR PERDERÁ(RÃO) 1 PONTO DO TIPO A.

OBS.:. Ao final da jogada de todos participantes, deverá ter uma mensagem PARA TODOS: VOCÊS PERDERAM 1 ITEM ESCOLAR E CADA UM PERDEU UMA QUANTIDADE DE PONTOS DO TIPO A. ESSA MENSAGEM DEVE SER EDITÁVEL PELO PESQUISADOR, no momento que for estruturar seu experimento.

**Condição 3**

Essa condição deverá ser iniciada com 80 itens escolares e 210 pontos do tipo do TIPO A para cada participante. Ou seja, permitir pontuação inicial por condição e não apenas por experimento.

2.4. Se algum (ou todos) dos participantes escolher LINHA ÍMPAR PERDERÁ 1 PONTO GRUPO (=1 item escolar).

OBS.: Ao final da jogada de todos participantes, deverá ter uma mensagem PARA TODOS: VOCÊS PERDERAM 1 ITEM ESCOLAR. ESSA MENSAGEM DEVE SER EDITÁVEL PELO PESQUISADOR, no momento que for estruturar seu experimento.

2.5. Após os participantes terem acesso a perda do item escolar, o software apresentará a seguinte questão:

> “Vocês gostariam de 'comprar' 1 item escolar? Todos devem clicar em SIM para confirmar à 'compra'. Caso não queiram 'comprar', todos devem clicar em NÃO." (com as opções SIM e NÃO)

OBS.: ESSA MENSAGEM DEVE SER EDITÁVEL PELO PESQUISADOR, no momento que for estruturar seu experimento.

2.5.1 Se todos selecionarem SIM, a quantidade de pontos retirada do TIPO A será de acordo com a linha escolhida pelo participante em sua jogada durante à rodada (ciclo=jogada de todos os membros do grupo):
- O(s) participante(s) que selecionou(ram) LINHA ÍMPAR PERDERÁ(RÃO) 3 PONTOS DO TIPO A.
- O(s) participante(s) que selecionou(ram) LINHA PAR PERDERÁ(RÃO) 1 PONTO DO TIPO A.
- 1 PONTO GRUPO SERÁ ADICIONADO NO CONTADOR e deverá ser apresentada uma mensagem a todos eles: VOCÊS COMPRARAM 1 ITEM ESCOLAR. ESSA MENSAGEM DEVE SER EDITÁVEL PELO PESQUISADOR, no momento que for estruturar seu experimento. INICIARÁ UMA NOVA RODADA.

2.5.2 Se ALGUM ou todos selecionarem NÃO, NENHUM PONTO SERÁ RETIRADO, MANTENDO A PERDA DE 1 ITEM ESCOLAR. INICIARÁ UMA NOVA RODADA.

**Comment by cpicanco** [comment]
Implementado
https://github.com/cpicanco/stimulus_control/tree/master/tests/lacs-matrix
