### ISSUE TITLE
Impedir logar com um mesmo usuário em vários computadores.

### ISSUE THREAD

**Issue by brunosilva87** [lacs-ufpa/mtrix#3]
Impedir logar com um mesmo usuário em vários computadores.

OBS.: Impedir logins simultâneos com o mesmo usuário.

**Comment by weslleysammyr** [comment]
Conforme conversa com o @cpicanco e com a @thaismguimaraes, este caso deve ser encerrado.

**Comment by cpicanco** [comment]
Embora impedir logins simultaneos seja possível e desejável (ver solução em [php](http://stackoverflow.com/questions/1727919/how-to-prevent-multiple-logins-in-php-website), por exemplo) não é uma prioridade. Login e senha bastam por hora...
